image_to_gstreamer_node:
  ros__parameters:
    input_topic: "/zed_node/left/image_rect_color"
    host: "10.0.0.154"
    port: 5001

    framerate: 15
    bitrate: 500000
    preset_level: 1
    iframe_interval: 15
    control_rate: 1
    pt: 96
    config_interval: 1
    format: "RGB"
  