<?xml version="1.0"?>
<package format="3">
  <name>image_to_gstreamer</name>
  <version>0.1.0</version>
  <description>takes image form ROS node and sends it via gstreamer</description>

  <maintainer email="gardeg@github.com">Gard</maintainer>
  <license>MIT</license>

  <buildtool_depend>ament_cmake</buildtool_depend>

  <depend>rclcpp</depend>
  <depend>sensor_msgs</depend>
  <depend>vortex_utils_ros</depend>
  
  

  <build_depend>pkg-config</build_depend>
  <exec_depend>pkg-config</exec_depend>

  <build_depend>libgstreamer1.0-dev</build_depend>
  <build_depend>libgstreamer-plugins-base1.0-dev</build_depend>
  <exec_depend>libgstreamer1.0-dev</exec_depend>
  <exec_depend>libgstreamer-plugins-base1.0-dev</exec_depend>

  <export>
    <build_type>ament_cmake</build_type>
  </export>
</package>
